apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: archideal

resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - runtime-controller-rbac.yaml
  - configuration.yaml
  - services.yaml
  - workloads.yaml
  - runtime-management.yaml
  - consumers.yaml
  - private-network-preflight.yaml
  - preflight.yaml
  - jobs.yaml
  - bootstrap.yaml
  - availability.yaml
  - autoscaling.yaml
  - network-policies.yaml
  - observability.yaml
