HOSTING_MODULE_CREATED = "hosting.module.created"
HOSTING_MODULE_UPDATED = "hosting.module.updated"
HOSTING_MODULE_DELETED = "hosting.module.deleted"
HOSTING_TOOL_CREATED = "hosting.tool.created"
HOSTING_TOOL_UPDATED = "hosting.tool.updated"
HOSTING_TOOL_DELETED = "hosting.tool.deleted"
HOSTING_TOOL_VERSION_RELEASED = "hosting.tool.version_released"
HOSTING_APPLICATION_CREATED = "hosting.application.created"
HOSTING_APPLICATION_UPDATED = "hosting.application.updated"
HOSTING_APPLICATION_DELETED = "hosting.application.deleted"
HOSTING_APPLICATION_VERSION_RELEASED = "hosting.application.version_released"
HOSTING_DATASET_CREATED = "hosting.dataset.created"
HOSTING_DATASET_UPDATED = "hosting.dataset.updated"
HOSTING_DATASET_DELETED = "hosting.dataset.deleted"

IAM_OIDC_ACL_IDENTITY_DEPROVISIONED = "iam.oidc_acl_identity.deprovisioned"

GATEWAY_ROUTE_PUBLISH_REQUESTED = "gateway.route.publish.requested"
GATEWAY_ROUTE_PUBLISH_COMPLETED = "gateway.route.publish.completed"
GATEWAY_ROUTE_PUBLISH_FAILED = "gateway.route.publish.failed"
GATEWAY_GITHUB_WEBHOOK_RECEIVED = "gateway.github.webhook.received"
