{
 "title": "Alerting / Target Status",
 "tags": [
  "alerting",
  "prometheus",
  "full"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Targets Down Now",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up == 0)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Flapping Targets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(changes(up[10m]) > 4)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Down Targets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "up == 0", "legendFormat": "{{job}} {{instance}}" }
   ]
  },
  {
   "title": "Target Flapping",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "changes(up[10m])", "legendFormat": "{{job}} {{instance}}" }
   ]
  }
 ]
}