# Generated by Django 6.0.7 on 2026-07-19 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensor_data", "0004_rename_wildfi_sensor_event_and_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensordata",
            name="sensor_data_sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sensor_data_sensor",
                to="sensor_data.sensor",
            ),
        ),
        migrations.AlterField(
            model_name="sensordataobservedobject",
            name="sensor_data_observed_object_sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sensor_data_observed_object_sensor",
                to="sensor_data.sensor",
            ),
        ),
        migrations.AlterField(
            model_name="sensorobservedobject",
            name="sensor_observed_object_sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sensor_observed_object_sensor",
                to="sensor_data.sensor",
            ),
        ),
    ]
