# Generated by Django 6.0.7 on 2026-07-19 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gps_data", "0004_rename_wildfigpsfix_gpsfix_and_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observedobjectgpssensor",
            name="observed_object_gps_sensor_gps_sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gps_sensor_link",
                to="gps_data.gpssensor",
            ),
        ),
        migrations.AlterField(
            model_name="processedgpsdataobservedobject",
            name="processed_gps_data_sensors",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gps_sensor_link2",
                to="gps_data.gpssensor",
            ),
        ),
    ]
