apiVersion: v1
kind: ConfigMap
metadata:
  name: dealhost-runtime-secret-catalog
  namespace: archideal-runtime-apps
  labels:
    app.kubernetes.io/part-of: archideal
    app.kubernetes.io/managed-by: archideal-operator
    archideal.io/runtime-secret-catalog: "true"
data: {}
