#!/usr/bin/env python3
"""Strictly render ArchiDEAL Kubernetes placeholders from a non-secret values file."""

from __future__ import annotations

import argparse
import ipaddress
from pathlib import Path
import re
import shutil
import sys
from urllib.parse import SplitResult, urlsplit

import yaml


ROOT = Path(__file__).resolve().parent
SUPPLY_CHAIN_POLICY = ROOT / "supply-chain-policy.yaml"
GENERATED_MARKER = ".archideal-kubernetes-render-v1"
GENERATED_MARKER_CONTENT = "generated by deploy/kubernetes/render.py; safe to replace\n"
PLACEHOLDER = re.compile(r"\$\{([A-Z][A-Z0-9_]*)\}")
IMAGE = re.compile(r"^[^\s@]+@sha256:([0-9a-f]{64})$")
DNS_LABEL = re.compile(r"^[a-z0-9](?:[-a-z0-9]{0,61}[a-z0-9])?$")
RELEASE = DNS_LABEL
HOST = re.compile(
    r"^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+"
    r"[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$"
)
SAFE_IDENTIFIER = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._:/-]{0,127}$")
SAFE_SECRET_PREFIX = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._/-]{2,254}$")
SAFE_URL_PATH = re.compile(r"^(?:/[A-Za-z0-9._~!$&()*+,;=:@%/-]*)?$")
RFC1918_NETWORKS = tuple(
    ipaddress.ip_network(cidr)
    for cidr in ("10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16")
)


class UniqueKeyLoader(yaml.SafeLoader):
    """Safe YAML loader that rejects duplicate and merge-overridden keys."""


def construct_unique_mapping(
    loader: UniqueKeyLoader,
    node: yaml.MappingNode,
    deep: bool = False,
) -> dict:
    loader.flatten_mapping(node)
    mapping: dict = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node, deep=deep)
        if key in mapping:
            raise yaml.constructor.ConstructorError(
                "while constructing a mapping",
                node.start_mark,
                f"duplicate key: {key!r}",
                key_node.start_mark,
            )
        mapping[key] = loader.construct_object(value_node, deep=deep)
    return mapping


UniqueKeyLoader.add_constructor(
    yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG,
    construct_unique_mapping,
)


def load_image_repository_policy() -> dict[str, str]:
    raw = yaml.load(
        SUPPLY_CHAIN_POLICY.read_text(encoding="utf-8"),
        Loader=UniqueKeyLoader,
    )
    image_keys = {name for name in REQUIRED if name.startswith("IMAGE_")}
    images = raw.get("images") if isinstance(raw, dict) else None
    if (
        not isinstance(raw, dict)
        or raw.get("schemaVersion") != "archideal.supply-chain-policy/v1"
        or not isinstance(images, dict)
        or set(images) != image_keys
    ):
        fail("The supply-chain policy must define exactly all production images.")
    repositories: dict[str, str] = {}
    for key, image in images.items():
        repository = image.get("repository") if isinstance(image, dict) else None
        if not isinstance(repository, str) or not repository or "@" in repository:
            fail(f"The supply-chain repository policy is invalid for {key}.")
        repositories[key] = repository
    return repositories

REQUIRED = {
    "RELEASE_ID",
    "PUBLIC_HOST",
    "INGRESS_CLASS",
    "INGRESS_NAMESPACE",
    "INGRESS_PROXY_CIDR",
    "TLS_SECRET_NAME",
    "CLUSTER_ISSUER",
    "SECRET_STORE_NAME",
    "SECRET_PREFIX",
    "OIDC_ISSUER_URL",
    "OIDC_INTROSPECTION_URL",
    "OIDC_ALLOWED_GROUP",
    "OIDC_AUDIENCE",
    "OIDC_EGRESS_CIDR",
    "GITHUB_EGRESS_CIDR",
    "KAFKA_BOOTSTRAP_SERVERS",
    "MQTT_HOST",
    "POSTGRES_METADATA_HOST",
    "POSTGRES_DATA_HOST",
    "VALKEY_HOST",
    "ETCD_ENDPOINT_1",
    "ETCD_ENDPOINT_2",
    "ETCD_ENDPOINT_3",
    "ETCD_TLS_SERVER_NAME",
    "KAFKA_EGRESS_CIDR",
    "MQTT_EGRESS_CIDR",
    "POSTGRES_METADATA_EGRESS_CIDR",
    "POSTGRES_DATA_EGRESS_CIDR",
    "VALKEY_EGRESS_CIDR",
    "ETCD_EGRESS_CIDR",
    "POD_CIDR",
    "OTEL_COLLECTOR_HTTP_ENDPOINT",
    "OTEL_EGRESS_CIDR",
    "MONITORING_NAMESPACE",
    "IMAGE_APISIX",
    "IMAGE_OAUTH2_PROXY",
    "IMAGE_APISIX_BOOTSTRAP",
    "IMAGE_MQTT_KAFKA_BRIDGE",
    "IMAGE_DEALIOT_CONSOLE",
    "IMAGE_DEALHOST",
    "IMAGE_DEALDATA_CORE",
    "IMAGE_DEALDATA_GPS",
    "IMAGE_DEALDATA_SENSOR",
    "IMAGE_DEALINTERFACE",
}


def fail(message: str) -> None:
    raise ValueError(message)


def is_dns_hostname(value: str) -> bool:
    if not HOST.fullmatch(value):
        return False
    try:
        ipaddress.ip_address(value)
    except ValueError:
        return True
    return False


def validate_render_scalar(key: str, value: str) -> None:
    """Reject characters that could escape a quoted YAML substitution context."""
    if any(
        ord(character) < 0x21
        or ord(character) > 0x7E
        or character in {'"', "'", "\\"}
        for character in value
    ):
        fail(
            f"{key} must use visible ASCII without whitespace, control characters, "
            "quotes or backslashes."
        )


def parse_https_endpoint(key: str, value: str) -> tuple[SplitResult, int]:
    """Parse a canonical HTTPS endpoint after the YAML-safety gate."""
    try:
        parsed = urlsplit(value)
        hostname = parsed.hostname
        port = parsed.port
    except ValueError as exc:
        fail(f"{key} is not a valid HTTPS URL: {exc}")

    if (
        parsed.scheme != "https"
        or not hostname
        or not is_dns_hostname(hostname)
        or parsed.username is not None
        or parsed.password is not None
        or parsed.fragment
        or parsed.query
    ):
        fail(
            f"{key} must be an HTTPS URL with a DNS hostname and without "
            "credentials, query or fragment."
        )

    expected_authority = hostname if port is None else f"{hostname}:{port}"
    if parsed.netloc != expected_authority:
        fail(f"{key} must use a canonical DNS hostname and numeric port.")
    if not SAFE_URL_PATH.fullmatch(parsed.path) or re.search(
        r"%(?![0-9A-Fa-f]{2})", parsed.path
    ):
        fail(f"{key} contains an invalid URL path.")

    return parsed, 443 if port is None else port


def load_values(path: Path, *, allow_example: bool) -> dict[str, str]:
    raw = yaml.load(path.read_text(encoding="utf-8"), Loader=UniqueKeyLoader)
    if not isinstance(raw, dict):
        fail("Values must be a flat YAML mapping.")
    if not all(isinstance(key, str) for key in raw):
        fail("Values keys must be strings.")
    if set(raw) != REQUIRED:
        missing = sorted(REQUIRED - set(raw))
        extra = sorted(set(raw) - REQUIRED)
        fail(f"Values keys mismatch; missing={missing}, extra={extra}")
    values: dict[str, str] = {}
    for key, value in raw.items():
        if not isinstance(value, str) or not value:
            fail(f"{key} must be a non-empty string.")
        validate_render_scalar(key, value)
        values[key] = value

    if not RELEASE.fullmatch(values["RELEASE_ID"]):
        fail("RELEASE_ID must be a lowercase DNS label.")
    if values["RELEASE_ID"] in {"none", "pending"}:
        fail("RELEASE_ID uses a reserved promotion-state sentinel.")
    if len(values["RELEASE_ID"]) > 39:
        fail(
            "RELEASE_ID must be at most 39 characters so every rendered "
            "Kubernetes Job name remains a valid DNS label."
        )
    for key in (
        "INGRESS_CLASS",
        "INGRESS_NAMESPACE",
        "TLS_SECRET_NAME",
        "CLUSTER_ISSUER",
        "SECRET_STORE_NAME",
        "MONITORING_NAMESPACE",
    ):
        value = values[key]
        if len(value) > 253 or not all(
            DNS_LABEL.fullmatch(label) for label in value.split(".")
        ):
            fail(f"{key} must be a DNS-1123 subdomain.")
    if (
        values["INGRESS_NAMESPACE"] == "archideal"
        or values["MONITORING_NAMESPACE"] == "archideal"
        or values["INGRESS_NAMESPACE"] == values["MONITORING_NAMESPACE"]
    ):
        fail(
            "INGRESS_NAMESPACE, MONITORING_NAMESPACE and the archideal application "
            "namespace must be distinct trust boundaries."
        )
    for key in (
        "PUBLIC_HOST",
        "MQTT_HOST",
        "POSTGRES_METADATA_HOST",
        "POSTGRES_DATA_HOST",
        "VALKEY_HOST",
        "ETCD_TLS_SERVER_NAME",
    ):
        if not is_dns_hostname(values[key]):
            fail(f"{key} must be a DNS hostname, without scheme or wildcard.")
    networks: dict[str, ipaddress.IPv4Network | ipaddress.IPv6Network] = {}
    for key in (
        "KAFKA_EGRESS_CIDR",
        "MQTT_EGRESS_CIDR",
        "POSTGRES_METADATA_EGRESS_CIDR",
        "POSTGRES_DATA_EGRESS_CIDR",
        "VALKEY_EGRESS_CIDR",
        "ETCD_EGRESS_CIDR",
        "POD_CIDR",
        "INGRESS_PROXY_CIDR",
        "OIDC_EGRESS_CIDR",
        "GITHUB_EGRESS_CIDR",
        "OTEL_EGRESS_CIDR",
    ):
        network = ipaddress.ip_network(values[key], strict=True)
        if network.prefixlen == 0:
            fail(f"{key} must not permit the whole Internet.")
        networks[key] = network
    private_dependency_keys = (
        "KAFKA_EGRESS_CIDR",
        "MQTT_EGRESS_CIDR",
        "POSTGRES_METADATA_EGRESS_CIDR",
        "POSTGRES_DATA_EGRESS_CIDR",
        "VALKEY_EGRESS_CIDR",
        "ETCD_EGRESS_CIDR",
    )
    for key in (*private_dependency_keys, "POD_CIDR", "INGRESS_PROXY_CIDR"):
        network = networks[key]
        if network.version != 4 or not any(
            network.subnet_of(private_network) for private_network in RFC1918_NETWORKS
        ):
            fail(f"{key} must be an IPv4 RFC1918 network.")
    for index, key in enumerate(private_dependency_keys):
        if networks[key].overlaps(networks["POD_CIDR"]):
            fail(f"{key} must not overlap POD_CIDR.")
        for other_key in private_dependency_keys[index + 1 :]:
            if networks[key].overlaps(networks[other_key]):
                fail(f"{key} must not overlap {other_key}.")
    for key in ("OIDC_EGRESS_CIDR", "GITHUB_EGRESS_CIDR", "OTEL_EGRESS_CIDR"):
        network = networks[key]
        minimum_prefix = 20 if network.version == 4 else 48
        if network.prefixlen < minimum_prefix:
            fail(
                f"{key} must be a change-reviewed provider range no broader than "
                f"/{minimum_prefix} for IPv{network.version}."
            )
        if networks[key].overlaps(networks["POD_CIDR"]):
            fail(f"{key} must not overlap POD_CIDR.")
    parsed_https_urls: dict[str, tuple[SplitResult, int]] = {}
    for key in (
        "OIDC_ISSUER_URL",
        "OIDC_INTROSPECTION_URL",
        "OTEL_COLLECTOR_HTTP_ENDPOINT",
        "ETCD_ENDPOINT_1",
        "ETCD_ENDPOINT_2",
        "ETCD_ENDPOINT_3",
    ):
        parsed_https_urls[key] = parse_https_endpoint(key, values[key])

    for index in range(1, 4):
        key = f"ETCD_ENDPOINT_{index}"
        if parsed_https_urls[key][0].path not in {"", "/"}:
            fail(f"{key} must not contain a path.")

    for key in ("OIDC_ISSUER_URL", "OIDC_INTROSPECTION_URL"):
        if parsed_https_urls[key][1] != 443:
            fail(f"{key} must use TCP port 443 allowed by the OIDC NetworkPolicies.")
    if parsed_https_urls["OTEL_COLLECTOR_HTTP_ENDPOINT"][1] != 443:
        fail(
            "OTEL_COLLECTOR_HTTP_ENDPOINT must use TCP port 443 allowed by the "
            "APISIX NetworkPolicy."
        )
    for index in range(1, 4):
        key = f"ETCD_ENDPOINT_{index}"
        if parsed_https_urls[key][1] != 2379:
            fail(f"{key} must use TCP port 2379 allowed by the APISIX NetworkPolicy.")
    brokers = values["KAFKA_BOOTSTRAP_SERVERS"].split(",")
    if len(set(brokers)) < 3:
        fail("KAFKA_BOOTSTRAP_SERVERS must list at least three brokers.")
    broker_hosts: set[str] = set()
    for broker in brokers:
        host, separator, port = broker.rpartition(":")
        if not separator or not is_dns_hostname(host) or not port.isdigit():
            fail("Each Kafka bootstrap server must be a DNS hostname and numeric port.")
        if int(port) != 9093:
            fail(
                "Each Kafka bootstrap server must use TCP port 9093 allowed by "
                "the runtime NetworkPolicy."
            )
        broker_hosts.add(host)
    if len(broker_hosts) < 3:
        fail("KAFKA_BOOTSTRAP_SERVERS must use at least three distinct hostnames.")
    etcd_urls = [values[f"ETCD_ENDPOINT_{index}"] for index in range(1, 4)]
    etcd_hosts = {
        parsed_https_urls[f"ETCD_ENDPOINT_{index}"][0].hostname
        for index in range(1, 4)
    }
    if len(set(etcd_urls)) != 3 or len(etcd_hosts) != 3:
        fail("The three etcd endpoints must use three distinct URLs and hostnames.")
    for key in ("OIDC_ALLOWED_GROUP", "OIDC_AUDIENCE"):
        if not SAFE_IDENTIFIER.fullmatch(values[key]) or ".." in values[key]:
            fail(f"{key} contains unsafe characters.")
    secret_prefix = values["SECRET_PREFIX"]
    if not SAFE_SECRET_PREFIX.fullmatch(secret_prefix) or ".." in secret_prefix:
        fail("SECRET_PREFIX contains unsafe characters.")
    image_repositories = load_image_repository_policy()
    for key in sorted(name for name in REQUIRED if name.startswith("IMAGE_")):
        match = IMAGE.fullmatch(values[key])
        if not match:
            fail(f"{key} must be an image reference pinned by sha256 digest.")
        if values[key].rsplit("@sha256:", 1)[0] != image_repositories[key]:
            fail(f"{key} must use the repository approved by supply-chain policy.")
        if not allow_example and match.group(1) == "0" * 64:
            fail(f"{key} still has the example all-zero digest.")

    if not allow_example:
        example_markers = (".invalid", "replace/", "example", "REPLACE")
        for key, value in values.items():
            if any(marker.lower() in value.lower() for marker in example_markers):
                fail(f"{key} still contains an example marker.")
    return values


def render_text(text: str, values: dict[str, str], path: Path) -> str:
    used = set(PLACEHOLDER.findall(text))
    unknown = used - set(values)
    if unknown:
        fail(f"{path}: unknown placeholders {sorted(unknown)}")
    rendered = PLACEHOLDER.sub(lambda match: values[match.group(1)], text)
    unresolved = PLACEHOLDER.findall(rendered)
    if unresolved:
        fail(f"{path}: unresolved placeholders {sorted(set(unresolved))}")
    return rendered


def validate_yaml_tree(root: Path) -> list[dict]:
    rendered_documents: list[dict] = []
    for path in sorted((*root.rglob("*.yaml"), *root.rglob("*.yml"))):
        try:
            documents = list(
                yaml.load_all(
                    path.read_text(encoding="utf-8"),
                    Loader=UniqueKeyLoader,
                )
            )
        except yaml.YAMLError as exc:
            fail(f"Invalid rendered YAML at {path}: {exc}")
        if not any(document is not None for document in documents):
            fail(f"Rendered YAML is empty: {path}")
        rendered_documents.extend(
            document for document in documents if isinstance(document, dict)
        )
    return rendered_documents


def validate_runtime_contracts(documents: list[dict]) -> None:
    workloads = {
        document["metadata"]["name"]: document
        for document in documents
        if document.get("kind") in {"Deployment", "StatefulSet"}
    }
    pod_owners = [
        document
        for document in documents
        if document.get("kind") in {"Deployment", "StatefulSet", "Job"}
    ]
    hpas = {
        document["spec"]["scaleTargetRef"]["name"]: document
        for document in documents
        if document.get("kind") == "HorizontalPodAutoscaler"
    }
    for workload in pod_owners:
        pod_spec = workload["spec"]["template"]["spec"]
        if pod_spec.get("nodeSelector") != {
            "kubernetes.io/os": "linux",
            "kubernetes.io/arch": "amd64",
        }:
            fail(
                f"{workload['metadata']['name']}: production images are released "
                "for linux/amd64 and require an exact nodeSelector."
            )
        pod_security = pod_spec.get("securityContext", {})
        if (
            pod_security.get("runAsNonRoot") is not True
            or pod_security.get("seccompProfile", {}).get("type")
            != "RuntimeDefault"
            or pod_spec.get("automountServiceAccountToken") is not False
        ):
            fail(
                f"{workload['metadata']['name']}: pod security baseline is incomplete."
            )
        for container in [
            *pod_spec.get("initContainers", []),
            *pod_spec.get("containers", []),
        ]:
            if not IMAGE.fullmatch(container.get("image", "")):
                fail(
                    f"{workload['metadata']['name']}/{container.get('name')}: "
                    "rendered image is not digest-pinned."
                )
            container_security = container.get("securityContext", {})
            if (
                container_security.get("allowPrivilegeEscalation") is not False
                or container_security.get("readOnlyRootFilesystem") is not True
                or container_security.get("runAsNonRoot") is not True
                or "ALL"
                not in container_security.get("capabilities", {}).get("drop", [])
            ):
                fail(
                    f"{workload['metadata']['name']}/{container.get('name')}: "
                    "restricted container security baseline is incomplete."
                )

    for workload in workloads.values():
        annotations = workload["spec"]["template"].get("metadata", {}).get(
            "annotations", {}
        )
        if not annotations.get("archideal.io/release"):
            fail(f"{workload['metadata']['name']}: PodTemplate lacks release revision.")
        name = workload["metadata"]["name"]
        hpa = hpas.get(name)
        if not hpa:
            fail(f"{name}: every long-running production workload requires an HPA.")
        if "replicas" in workload["spec"]:
            fail(
                f"{name}: HPA must be the sole field owner of scale; "
                "spec.replicas is forbidden."
            )
        if hpa["spec"].get("minReplicas", 1) >= 3:
            zone_constraints = [
                constraint
                for constraint in workload["spec"]["template"]["spec"].get(
                    "topologySpreadConstraints", []
                )
                if constraint.get("topologyKey") == "topology.kubernetes.io/zone"
            ]
            if len(zone_constraints) != 1 or zone_constraints[0].get("minDomains") != 3:
                fail(
                    f"{name}: three-replica production "
                    "workloads must require three topology domains."
                )

    for name in (
        "dealdata-core",
        "dealdata-gps",
        "dealdata-sensor",
        "dealdata-gps-consumer",
        "dealdata-sensor-consumer",
        "dealiot-console",
        "mqtt-kafka-bridge",
    ):
        security = workloads[name]["spec"]["template"]["spec"]["securityContext"]
        if security.get("runAsUser") != 10001 or security.get("runAsGroup") != 10001:
            fail(f"{name} must override the image with numeric UID/GID 10001.")

    interface_security = workloads["dealinterface"]["spec"]["template"]["spec"][
        "securityContext"
    ]
    if interface_security.get("fsGroup") != 101:
        fail("DEALInterface nginx writable emptyDirs require fsGroup 101.")

    for job in (document for document in pod_owners if document.get("kind") == "Job"):
        if job["metadata"]["name"].startswith("dealdata-"):
            security = job["spec"]["template"]["spec"]["securityContext"]
            if security.get("runAsUser") != 10001:
                fail(f"{job['metadata']['name']} must use numeric UID 10001.")

    kafka_preflight = next(
        document
        for document in pod_owners
        if document.get("kind") == "Job"
        and document.get("metadata", {}).get("labels", {}).get(
            "app.kubernetes.io/name"
        )
        == "kafka-preflight"
    )
    preflight_container = kafka_preflight["spec"]["template"]["spec"]["containers"][0]
    if preflight_container.get("command") != [
        "python",
        "-m",
        "dealdata_common.kafka_preflight",
    ]:
        fail("Kafka preflight must invoke the shared DEALData contract module.")
    preflight_env = {
        item["name"]: item for item in preflight_container.get("env", [])
    }
    required_topics = {
        "raw.sensor",
        "raw.gps",
        "raw.image2d.meta",
        "raw.image3d.meta",
        "raw.video2d.meta",
        "raw.video3d.meta",
        "dlq.events",
    }
    configured_topics = {
        topic.strip()
        for topic in preflight_env.get("KAFKA_PREFLIGHT_TOPICS", {})
        .get("value", "")
        .split(",")
        if topic.strip()
    }
    thresholds = {
        name: preflight_env.get(name, {}).get("value")
        for name in (
            "KAFKA_PREFLIGHT_MIN_PARTITIONS",
            "KAFKA_PREFLIGHT_MIN_REPLICATION_FACTOR",
            "KAFKA_PREFLIGHT_MIN_IN_SYNC_REPLICAS",
        )
    }
    if configured_topics != required_topics or thresholds != {
        "KAFKA_PREFLIGHT_MIN_PARTITIONS": "3",
        "KAFKA_PREFLIGHT_MIN_REPLICATION_FACTOR": "3",
        "KAFKA_PREFLIGHT_MIN_IN_SYNC_REPLICAS": "2",
    }:
        fail("Kafka preflight topic, partition, replication or ISR contract is incomplete.")
    preflight_user_ref = preflight_env["DEALDATA_KAFKA_SASL_USERNAME"][
        "valueFrom"
    ]["secretKeyRef"]["key"]
    if preflight_user_ref != "kafka-consumer-username":
        fail("Kafka preflight must use the scoped consumer/describe credential.")

    private_network_preflight = next(
        (
            document
            for document in pod_owners
            if document.get("kind") == "Job"
            and document.get("metadata", {}).get("labels", {}).get(
                "app.kubernetes.io/name"
            )
            == "private-network-preflight"
        ),
        None,
    )
    if not private_network_preflight:
        fail("The private dependency DNS preflight Job is missing.")
    private_preflight_spec = private_network_preflight["spec"]["template"]["spec"]
    private_preflight_containers = private_preflight_spec.get("containers", [])
    if len(private_preflight_containers) != 1:
        fail("Private dependency DNS preflight must have exactly one container.")
    private_preflight_container = private_preflight_containers[0]
    private_preflight_env = {
        item.get("name"): item for item in private_preflight_container.get("env", [])
    }
    expected_private_env = {
        "KAFKA_BOOTSTRAP_SERVERS",
        "KAFKA_EGRESS_CIDR",
        "MQTT_HOST",
        "MQTT_EGRESS_CIDR",
        "POSTGRES_METADATA_HOST",
        "POSTGRES_METADATA_EGRESS_CIDR",
        "POSTGRES_DATA_HOST",
        "POSTGRES_DATA_EGRESS_CIDR",
        "VALKEY_HOST",
        "VALKEY_EGRESS_CIDR",
        "ETCD_ENDPOINT_1",
        "ETCD_ENDPOINT_2",
        "ETCD_ENDPOINT_3",
        "ETCD_EGRESS_CIDR",
    }
    if (
        private_network_preflight["spec"].get("backoffLimit") != 0
        or private_preflight_spec.get("serviceAccountName") != "archideal-preflight"
        or private_preflight_spec.get("initContainers")
        or private_preflight_spec.get("volumes")
        or private_preflight_container.get("command")
        != ["python", "/bootstrap/private_network_preflight.py"]
        or private_preflight_container.get("envFrom")
        or private_preflight_container.get("volumeMounts")
        or set(private_preflight_env) != expected_private_env
        or any(
            "value" not in item or "valueFrom" in item
            for item in private_preflight_env.values()
        )
    ):
        fail(
            "Private dependency DNS preflight must be a non-secret, no-retry "
            "cluster resolution gate."
        )

    apisix = workloads.get("apisix")
    if not apisix:
        fail("Rendered baseline is missing the APISIX Deployment.")
    apisix_pod = apisix["spec"]["template"]["spec"]
    pod_security = apisix_pod.get("securityContext", {})
    if pod_security.get("runAsUser") != 636 or pod_security.get("fsGroup") != 636:
        fail("APISIX must use the image's validated non-root UID/GID 636 contract.")
    apisix_container = next(
        container for container in apisix_pod["containers"] if container["name"] == "apisix"
    )
    apisix_health = next(
        (
            container
            for container in apisix_pod["containers"]
            if container["name"] == "apisix-health"
        ),
        None,
    )
    prepare = next(
        (
            container
            for container in apisix_pod.get("initContainers", [])
            if container["name"] == "prepare-runtime"
        ),
        None,
    )
    if not prepare or not apisix_container.get("securityContext", {}).get(
        "readOnlyRootFilesystem"
    ):
        fail("APISIX requires the non-root runtime preparation initContainer and read-only root.")
    if (
        not apisix_health
        or apisix_health.get("command") != ["python", "/bootstrap/health.py"]
        or apisix_health.get("args", [])[:2]
        != [
            "--upstream",
            "http://127.0.0.1:9091/apisix/prometheus/metrics",
        ]
        or apisix_container.get("readinessProbe", {}).get("httpGet")
        != {"path": "/readyz", "port": 9191}
        or apisix_health.get("readinessProbe", {}).get("httpGet")
        != {"path": "/readyz", "port": "health"}
        or apisix_health.get("livenessProbe", {}).get("httpGet")
        != {"path": "/healthz", "port": "health"}
    ):
        fail("APISIX readiness must fail closed on its bounded etcd reachability sidecar.")
    volume_names = {volume["name"] for volume in apisix_pod.get("volumes", [])}
    if "runtime" not in volume_names:
        fail("APISIX requires a writable runtime emptyDir.")
    apisix_config_map = next(
        document
        for document in documents
        if document.get("kind") == "ConfigMap"
        and document.get("metadata", {}).get("name") == "apisix-production-config"
    )
    apisix_config = yaml.load(
        apisix_config_map["data"]["config.yaml"],
        Loader=UniqueKeyLoader,
    )
    trusted_ca = apisix_config.get("apisix", {}).get("ssl", {}).get(
        "ssl_trusted_certificate"
    )
    etcd_tls = apisix_config.get("deployment", {}).get("etcd", {}).get("tls", {})
    if trusted_ca != "/var/run/archideal-ca/etcd-ca.crt" or {
        "verify": True,
        "cert": "/var/run/archideal-ca/etcd-client.crt",
        "key": "/var/run/archideal-ca/etcd-client.key",
    }.items() - etcd_tls.items():
        fail("APISIX external etcd must use verified mutual TLS and the private CA.")
    ca_volume = next(volume for volume in apisix_pod["volumes"] if volume["name"] == "ca")
    mounted_etcd_keys = {
        item["key"] for item in ca_volume.get("secret", {}).get("items", [])
    }
    if not {"etcd-ca.crt", "etcd-client.crt", "etcd-client.key"} <= mounted_etcd_keys:
        fail("APISIX etcd CA and client key pair must be mounted from ExternalSecret.")

    console = workloads.get("dealiot-console")
    if not console:
        fail("Rendered baseline is missing the DEALIoT management console Deployment.")
    console_container = console["spec"]["template"]["spec"]["containers"][0]
    if console_container.get("readinessProbe", {}).get("httpGet") != {
        "path": "/readyz",
        "port": "http",
    }:
        fail("DEALIoT console readiness must fail closed on MQTT and Kafka reachability.")

    for name in ("dealdata-core", "dealdata-gps", "dealdata-sensor"):
        containers = workloads[name]["spec"]["template"]["spec"]["containers"]
        container = containers[0]
        service_port = {
            "dealdata-core": 7000,
            "dealdata-gps": 7001,
            "dealdata-sensor": 7002,
        }[name]
        env = {
            item["name"]: item.get("value")
            for item in container.get("env", [])
        }
        if env.get("RUN_MIGRATIONS") != "0" or env.get("RUN_COLLECTSTATIC") != "0":
            fail(f"{name} must disable entrypoint migrations and collectstatic.")
        if "command" in container or not container.get("args") or container["args"][0] != "granian":
            fail(f"{name} must preserve the hardened image entrypoint and pass granian as args.")
        for probe_name in ("startupProbe", "readinessProbe", "livenessProbe"):
            http_get = container.get(probe_name, {}).get("httpGet")
            if not http_get:
                continue
            headers = {
                header["name"].lower(): header["value"]
                for header in http_get.get("httpHeaders", [])
            }
            if headers.get("host") != name:
                fail(f"{name}/{probe_name} must send an allowed Django Host header.")
        metrics_proxy = next(
            (item for item in containers if item.get("name") == "metrics-proxy"),
            None,
        )
        metrics_proxy_args = metrics_proxy.get("args", []) if metrics_proxy else []
        if (
            not metrics_proxy
            or metrics_proxy.get("command")
            != ["python", "-m", "dealdata_common.metrics_proxy"]
            or metrics_proxy_args[:6]
            != [
                "--upstream",
                f"http://127.0.0.1:{service_port}/metrics/",
                "--upstream-ready",
                f"http://127.0.0.1:{service_port}/health/ready/",
                "--upstream-host",
                name,
            ]
            or not any(
                port.get("name") == "metrics" and port.get("containerPort") == 9101
                for port in metrics_proxy.get("ports", [])
            )
        ):
            fail(
                f"{name} must expose metrics through the isolated port 9101 proxy "
                "with a cheap, dependency-aware readiness path."
            )

    for name in ("dealdata-gps-consumer", "dealdata-sensor-consumer"):
        container = workloads[name]["spec"]["template"]["spec"]["containers"][0]
        if "command" in container or container.get("args", [])[:3] != [
            "python",
            "manage.py",
            "consume_dealiot_kafka",
        ]:
            fail(f"{name} must preserve the hardened image entrypoint.")

    dealhost = workloads["dealhost"]["spec"]["template"]["spec"]["containers"][0]
    dealhost_env = {item["name"]: item for item in dealhost.get("env", [])}
    if dealhost_env.get("DJANGO_SETTINGS_MODULE", {}).get("value") != "dealhost.settings.prod":
        fail("DEALHost must load its native fail-closed production settings.")
    password_ref = dealhost_env.get("DEALHOST_DATABASE_PASSWORD", {}).get(
        "valueFrom", {}
    ).get("secretKeyRef", {})
    if password_ref.get("key") != "dealhost-database-password":
        fail("DEALHost PostgreSQL password must come from ExternalSecret.")
    dealhost_valkey_ref = dealhost_env.get("VALKEY_URL", {}).get(
        "valueFrom", {}
    ).get("secretKeyRef", {})
    if dealhost_valkey_ref.get("key") != "valkey-url":
        fail("DEALHost must read its production Valkey TLS URL from ExternalSecret.")
    dealhost_migration = next(
        owner
        for owner in pod_owners
        if owner.get("kind") == "Job"
        and owner.get("metadata", {}).get("labels", {}).get("app.kubernetes.io/name")
        == "dealhost-migrate"
    )
    migration_container = dealhost_migration["spec"]["template"]["spec"]["containers"][0]
    migration_env = {item["name"]: item for item in migration_container.get("env", [])}
    migration_password_ref = migration_env.get("DEALHOST_DATABASE_PASSWORD", {}).get(
        "valueFrom", {}
    ).get("secretKeyRef", {})
    if (
        migration_env.get("DJANGO_SETTINGS_MODULE", {}).get("value")
        != "dealhost.settings.migration"
        or set(migration_env) != {"DJANGO_SETTINGS_MODULE", "DEALHOST_DATABASE_PASSWORD"}
        or migration_password_ref.get("key") != "dealhost-database-password"
    ):
        fail("DEALHost migrations must receive only their PostgreSQL credential.")
    dealhost_probe_paths = {
        "startupProbe": "/api/gateway/health/live/",
        "readinessProbe": "/api/gateway/health/ready/",
        "livenessProbe": "/api/gateway/health/live/",
    }
    for probe_name, expected_path in dealhost_probe_paths.items():
        http_get = dealhost.get(probe_name, {}).get("httpGet", {})
        headers = {
            header["name"].lower(): header["value"]
            for header in http_get.get("httpHeaders", [])
        }
        if http_get.get("path") != expected_path:
            fail(f"DEALHost {probe_name} must use {expected_path}.")
        if headers.get("host") != "dealhost" or headers.get(
            "x-forwarded-proto"
        ) != "https":
            fail(
                f"DEALHost {probe_name} must send its allowed Host and HTTPS proxy headers."
            )

    runtime_config = next(
        document
        for document in documents
        if document.get("kind") == "ConfigMap"
        and document.get("metadata", {}).get("name") == "archideal-runtime"
    )["data"]
    required_dealhost_config = {
        "DEALHOST_DATABASE_ENGINE",
        "DEALHOST_DATABASE_HOST",
        "DEALHOST_DATABASE_NAME",
        "DEALHOST_DATABASE_USER",
        "DEALHOST_DATABASE_PORT",
        "DEALHOST_DATABASE_SSLMODE",
        "DEALHOST_DATABASE_SSLROOTCERT",
        "DEALHOST_OIDC_INTROSPECTION_URL",
        "DEALHOST_OIDC_ISSUER",
        "DEALHOST_OIDC_AUDIENCE",
        "DEALHOST_OIDC_READ_GROUPS",
        "DEALHOST_OIDC_ADMIN_GROUPS",
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        "DEALHOST_SCRIPT_NAME",
    }
    if not required_dealhost_config <= runtime_config.keys():
        fail("DEALHost native production database/OIDC configuration is incomplete.")
    if (
        runtime_config["DJANGO_CSRF_TRUSTED_ORIGINS"]
        != f"https://{runtime_config['PUBLIC_HOST']}"
        or runtime_config["DEALHOST_SCRIPT_NAME"] != "/dealhost"
    ):
        fail("DEALHost public CSRF origin and script prefix must match the gateway route.")
    dealdata_users = {
        runtime_config.get("DEALDATA_CORE_DATABASE_USER"),
        runtime_config.get("DEALDATA_GPS_DATABASE_USER"),
        runtime_config.get("DEALDATA_SENSOR_DATABASE_USER"),
    }
    if dealdata_users != {"dealdata_core", "dealdata_gps", "dealdata_sensor"}:
        fail("Each DEALData layer must use a distinct least-privilege database role.")

    expected_database_refs = {
        "dealdata-core": (
            "DEALDATA_CORE_DATABASE_USER",
            "dealdata-core-database-password",
        ),
        "dealdata-core-migrate": (
            "DEALDATA_CORE_DATABASE_USER",
            "dealdata-core-database-password",
        ),
        "dealdata-gps": (
            "DEALDATA_GPS_DATABASE_USER",
            "dealdata-gps-database-password",
        ),
        "dealdata-gps-consumer": (
            "DEALDATA_GPS_DATABASE_USER",
            "dealdata-gps-database-password",
        ),
        "dealdata-gps-migrate": (
            "DEALDATA_GPS_DATABASE_USER",
            "dealdata-gps-database-password",
        ),
        "dealdata-sensor": (
            "DEALDATA_SENSOR_DATABASE_USER",
            "dealdata-sensor-database-password",
        ),
        "dealdata-sensor-consumer": (
            "DEALDATA_SENSOR_DATABASE_USER",
            "dealdata-sensor-database-password",
        ),
        "dealdata-sensor-migrate": (
            "DEALDATA_SENSOR_DATABASE_USER",
            "dealdata-sensor-database-password",
        ),
    }
    owners_by_name = {
        owner["metadata"].get("labels", {}).get("app.kubernetes.io/name"): owner
        for owner in pod_owners
        if owner["metadata"].get("labels", {}).get("app.kubernetes.io/name")
        in expected_database_refs
    }
    if set(owners_by_name) != set(expected_database_refs):
        fail("The rendered DEALData database credential owners are incomplete.")
    for owner_name, (user_key, password_key) in expected_database_refs.items():
        application_container = owners_by_name[owner_name]["spec"]["template"]["spec"][
            "containers"
        ][0]
        owner_env = {item["name"]: item for item in application_container.get("env", [])}
        rendered_user_key = (
            owner_env.get("DATABASE_USER", {})
            .get("valueFrom", {})
            .get("configMapKeyRef", {})
            .get("key")
        )
        rendered_password_key = (
            owner_env.get("DATABASE_PASSWORD", {})
            .get("valueFrom", {})
            .get("secretKeyRef", {})
            .get("key")
        )
        if rendered_user_key != user_key or rendered_password_key != password_key:
            fail(f"{owner_name} does not use its layer-scoped database credential.")

    oauth_pod = workloads["oauth2-proxy"]["spec"]["template"]["spec"]
    oauth = oauth_pod["containers"][0]
    oauth_args = set(oauth.get("args", []))
    required_oauth_args = {
        "--skip-jwt-bearer-tokens=true",
        "--bearer-token-login-fallback=false",
        "--pass-access-token=true",
        "--cookie-name=__Host-archideal",
        "--cookie-secure=true",
        "--cookie-httponly=true",
        "--session-store-type=redis",
    }
    if not required_oauth_args <= oauth_args:
        fail("oauth2-proxy is missing a mandatory fail-closed edge option.")
    allowed_bypass = {
        "--skip-auth-route=POST=^/dealhost/api/gateway/github/webhook/$"
    }
    configured_bypass = {
        argument for argument in oauth_args if argument.startswith("--skip-auth-route=")
    }
    if configured_bypass != allowed_bypass:
        fail("oauth2-proxy permits only the exact HMAC-authenticated GitHub webhook bypass.")
    if not any(argument.startswith("--extra-jwt-issuers=https://") for argument in oauth_args):
        fail("oauth2-proxy must validate bearer-token issuer and audience.")
    oauth_env = {item["name"]: item for item in oauth.get("env", [])}
    redis_ref = oauth_env.get("OAUTH2_PROXY_REDIS_CONNECTION_URL", {}).get(
        "valueFrom", {}
    ).get("secretKeyRef", {})
    if redis_ref.get("key") != "valkey-url":
        fail("oauth2-proxy HA sessions must use the external Valkey TLS URL.")
    valkey_validator = next(
        (
            container
            for container in oauth_pod.get("initContainers", [])
            if container.get("name") == "validate-valkey-tls"
        ),
        None,
    )
    validator_env = {
        item["name"]: item
        for item in valkey_validator.get("env", [])
    } if valkey_validator else {}
    validator_ref = validator_env.get("VALKEY_URL", {}).get(
        "valueFrom", {}
    ).get("secretKeyRef", {})
    if (
        not valkey_validator
        or valkey_validator.get("image") != dealhost.get("image")
        or valkey_validator.get("command") != ["python", "-c"]
        or "cache_config(require_tls=True)"
        not in " ".join(valkey_validator.get("args", []))
        or validator_ref.get("key") != "valkey-url"
    ):
        fail("oauth2-proxy must block startup unless its Valkey URL uses TLS.")

    oauth_policy = next(
        document
        for document in documents
        if document.get("kind") == "NetworkPolicy"
        and document.get("metadata", {}).get("name") == "oauth2-proxy-egress"
    )
    oauth_egress_ports = {
        port["port"]
        for rule in oauth_policy["spec"].get("egress", [])
        for port in rule.get("ports", [])
    }
    if 6380 not in oauth_egress_ports:
        fail("oauth2-proxy NetworkPolicy must allow the external Valkey TLS port.")

    network_policies = {
        document["metadata"]["name"]: document
        for document in documents
        if document.get("kind") == "NetworkPolicy"
    }
    expected_egress_ports = {
        "dealhost-external-egress": {443, 5432, 6380},
        "dealhost-migration-egress": {5432},
        "dealdata-api-egress": {5432},
        "dealdata-consumer-egress": {5432, 9093},
        "dealdata-migration-egress": {5432},
        "kafka-preflight-egress": {9093},
        "dealiot-console-egress": {443, 8883, 9093},
        "mqtt-kafka-bridge-egress": {8883, 9093},
        "production-smoke-egress": {8883},
    }
    for policy_name, expected_ports in expected_egress_ports.items():
        policy = network_policies.get(policy_name)
        if not policy:
            fail(f"Missing least-privilege dependency policy: {policy_name}.")
        actual_ports = {
            port["port"]
            for rule in policy["spec"].get("egress", [])
            for port in rule.get("ports", [])
        }
        if actual_ports != expected_ports:
            fail(f"{policy_name} has an unexpected external dependency port set.")
    if "runtime-external-dependencies" in network_policies:
        fail("The broad runtime external dependency policy is forbidden.")

    apisix_policy = next(
        document
        for document in documents
        if document.get("kind") == "NetworkPolicy"
        and document.get("metadata", {}).get("name") == "apisix-egress"
    )
    apisix_egress_ports = {
        port["port"]
        for rule in apisix_policy["spec"].get("egress", [])
        for port in rule.get("ports", [])
    }
    if not {443, 2379} <= apisix_egress_ports:
        fail("APISIX NetworkPolicy must allow OTLP HTTPS/443 and etcd TLS/2379.")

    policies = {
        document["metadata"]["name"]: document
        for document in documents
        if document.get("kind") == "NetworkPolicy"
    }
    monitoring_policy_ports = {
        "monitoring-identity-ingress": {44180},
        "monitoring-dealdata-ingress": {9101},
        "monitoring-ingestion-ingress": {8080, 9100},
    }
    for policy_name, expected_ports in monitoring_policy_ports.items():
        policy = policies.get(policy_name)
        if not policy:
            fail(f"Missing isolated monitoring policy: {policy_name}.")
        actual_ports = {
            port["port"]
            for rule in policy["spec"].get("ingress", [])
            for port in rule.get("ports", [])
        }
        if actual_ports != expected_ports:
            fail(f"{policy_name} exposes unexpected workload ports to monitoring.")
        for rule in policy["spec"].get("ingress", []):
            for source in rule.get("from", []):
                if source.get("podSelector", {}).get("matchLabels", {}).get(
                    "monitoring.archideal.io/scraper"
                ) != "true":
                    fail(f"{policy_name} must admit only labelled scraper pods.")

    services = {
        document["metadata"]["name"]: document
        for document in documents
        if document.get("kind") == "Service"
    }
    for name in ("dealdata-core", "dealdata-gps", "dealdata-sensor"):
        metrics_ports = [
            port
            for port in services[name]["spec"].get("ports", [])
            if port.get("name") == "metrics"
        ]
        if metrics_ports != [{"name": "metrics", "port": 9101, "targetPort": "metrics"}]:
            fail(f"Service/{name} must expose only the isolated metrics target on port 9101.")

    external_secrets = [
        document for document in documents if document.get("kind") == "ExternalSecret"
    ]
    runtime_external_secrets = [
        item
        for item in external_secrets
        if item.get("metadata", {}).get("name", "").startswith(
            "archideal-runtime-secrets-"
        )
    ]
    if (
        len(external_secrets) != 2
        or len(runtime_external_secrets) != 1
        or "archideal-registry-credentials"
        not in {item["metadata"]["name"] for item in external_secrets}
    ):
        fail("Exactly the runtime and registry ExternalSecrets must be rendered.")
    for external_secret in external_secrets:
        name = external_secret["metadata"]["name"]
        spec = external_secret.get("spec", {})
        target = spec.get("target", {})
        data = spec.get("data", [])
        secret_keys_for_target = [item.get("secretKey") for item in data]
        if (
            external_secret.get("apiVersion") != "external-secrets.io/v1"
            or spec.get("secretStoreRef", {}).get("kind") != "ClusterSecretStore"
            or not spec.get("secretStoreRef", {}).get("name")
            or target.get("name") != name
            or target.get("creationPolicy") != "Owner"
            or target.get("deletionPolicy") != "Retain"
            or not data
            or len(secret_keys_for_target) != len(set(secret_keys_for_target))
            or any(
                not item.get("secretKey")
                or not item.get("remoteRef", {}).get("key")
                for item in data
            )
        ):
            fail(f"ExternalSecret/{name} violates the production CRD contract.")

    registry_external_secret = next(
        item
        for item in external_secrets
        if item["metadata"]["name"] == "archideal-registry-credentials"
    )
    if (
        registry_external_secret["spec"].get("refreshPolicy") != "Periodic"
        or registry_external_secret["spec"].get("refreshInterval") != "1h"
        or registry_external_secret["spec"]["target"]["template"].get("type")
        != "kubernetes.io/dockerconfigjson"
    ):
        fail("The private registry ExternalSecret must be a docker config Secret.")
    runtime_external_secret = runtime_external_secrets[0]
    runtime_release = runtime_external_secret.get("metadata", {}).get("labels", {}).get(
        "archideal.io/release"
    )
    runtime_secret_name = f"archideal-runtime-secrets-{runtime_release}"
    runtime_spec = runtime_external_secret["spec"]
    runtime_target = runtime_spec["target"]
    if (
        not runtime_release
        or runtime_external_secret["metadata"]["name"] != runtime_secret_name
        or runtime_target.get("name") != runtime_secret_name
        or runtime_spec.get("refreshPolicy") != "CreatedOnce"
        or "refreshInterval" in runtime_spec
        or runtime_target.get("template", {})
        .get("metadata", {})
        .get("labels", {})
        .get("archideal.io/release")
        != runtime_release
    ):
        fail(
            "The runtime ExternalSecret must be CreatedOnce and scoped to exactly one release."
        )

    for owner in pod_owners:
        owner_release = (
            owner.get("spec", {})
            .get("template", {})
            .get("metadata", {})
            .get("annotations", {})
            .get("archideal.io/release")
            or owner.get("metadata", {})
            .get("labels", {})
            .get("archideal.io/release")
        )
        if owner_release != runtime_release:
            fail(
                f"{owner['metadata']['name']}: Pod owner and runtime Secret "
                "must use the same release."
            )
        pod_spec = owner["spec"]["template"]["spec"]
        for container in [
            *pod_spec.get("initContainers", []),
            *pod_spec.get("containers", []),
        ]:
            for environment in container.get("env", []):
                secret_ref = environment.get("valueFrom", {}).get("secretKeyRef")
                if secret_ref and secret_ref.get("name") != runtime_secret_name:
                    fail(
                        f"{owner['metadata']['name']}/{container['name']}: "
                        "Secret reference is not release-scoped."
                    )
            for environment_from in container.get("envFrom", []):
                secret_ref = environment_from.get("secretRef")
                if secret_ref and secret_ref.get("name") != runtime_secret_name:
                    fail(
                        f"{owner['metadata']['name']}/{container['name']}: "
                        "Secret envFrom is not release-scoped."
                    )
        for volume in pod_spec.get("volumes", []):
            secret_name = volume.get("secret", {}).get("secretName")
            if secret_name and secret_name != runtime_secret_name:
                fail(
                    f"{owner['metadata']['name']}/{volume['name']}: "
                    "Secret volume is not release-scoped."
                )
    secret_keys = {
        item["secretKey"] for item in runtime_external_secret["spec"].get("data", [])
    }
    runtime_secret_items = {
        item["secretKey"]: item
        for item in runtime_external_secret["spec"].get("data", [])
    }
    valkey_remote_key = runtime_secret_items.get("valkey-url", {}).get(
        "remoteRef", {}
    ).get("key", "")
    if not valkey_remote_key.endswith("/valkey/tls-url"):
        fail("The production Valkey URL must come from the dedicated TLS secret entry.")
    scoped_kafka_keys = {
        "kafka-console-username",
        "kafka-console-password",
        "kafka-producer-username",
        "kafka-producer-password",
        "kafka-consumer-username",
        "kafka-consumer-password",
    }
    if not scoped_kafka_keys <= secret_keys or {
        "kafka-sasl-username",
        "kafka-sasl-password",
    } & secret_keys:
        fail("Kafka console, producer and consumer credentials must be separated.")
    if not {"mqtt-smoke-username", "mqtt-smoke-password"} <= secret_keys:
        fail("The production synthetic requires a dedicated MQTT publish-only credential.")

    synthetic_job = next(
        (
            document
            for document in documents
            if document.get("kind") == "Job"
            and document.get("metadata", {}).get("labels", {}).get(
                "app.kubernetes.io/name"
            )
            == "production-smoke"
        ),
        None,
    )
    if not synthetic_job:
        fail("The production MQTT-to-database synthetic Job is missing.")
    synthetic_container = synthetic_job["spec"]["template"]["spec"]["containers"][0]
    synthetic_env = {item["name"]: item for item in synthetic_container.get("env", [])}
    synthetic_release = synthetic_job["metadata"].get("labels", {}).get(
        "archideal.io/release"
    )
    if (
        synthetic_container.get("command")
        != ["python", "-m", "management_console.synthetic_publish"]
        or synthetic_env.get("MQTT_USERNAME", {})
        .get("valueFrom", {})
        .get("secretKeyRef", {})
        .get("key")
        != "mqtt-smoke-username"
        or synthetic_env.get("MQTT_PASSWORD", {})
        .get("valueFrom", {})
        .get("secretKeyRef", {})
        .get("key")
        != "mqtt-smoke-password"
        or not isinstance(synthetic_release, str)
        or synthetic_env.get("SMOKE_DEVICE_ID", {}).get("value")
        != f"archideal-smoke-{synthetic_release}"
    ):
        fail(
            "The production synthetic must use its bounded publisher, scoped credential "
            "and release-derived template identity."
        )

    apisix_bootstrap_job = next(
        (
            document
            for document in documents
            if document.get("kind") == "Job"
            and document.get("metadata", {}).get("labels", {}).get(
                "app.kubernetes.io/name"
            )
            == "apisix-bootstrap"
        ),
        None,
    )
    if (
        not apisix_bootstrap_job
        or apisix_bootstrap_job.get("metadata", {}).get("name")
        != f"apisix-bootstrap-{synthetic_release}"
    ):
        fail("The APISIX bootstrap Job template must be scoped to the rendered release.")
    service_accounts = [
        document for document in documents if document.get("kind") == "ServiceAccount"
    ]
    for account in service_accounts:
        pull_names = {item["name"] for item in account.get("imagePullSecrets", [])}
        if "archideal-registry-credentials" not in pull_names:
            fail(f"{account['metadata']['name']} lacks private GHCR credentials.")

    ingresses = [document for document in documents if document.get("kind") == "Ingress"]
    for ingress in ingresses:
        for rule in ingress["spec"].get("rules", []):
            for path in rule.get("http", {}).get("paths", []):
                if path["backend"]["service"]["name"] != "oauth2-proxy":
                    fail("Every public Ingress path must terminate at oauth2-proxy.")

    config = next(
        document
        for document in documents
        if document.get("kind") == "ConfigMap"
        and document.get("metadata", {}).get("name") == "apisix-bootstrap"
    )
    routes = yaml.load(
        config["data"]["routes.json"],
        Loader=UniqueKeyLoader,
    )["routes"]
    protected = {route["id"]: route for route in routes}
    for route_id, route in protected.items():
        forwarded_proto = (
            route.get("plugins", {})
            .get("proxy-rewrite", {})
            .get("headers", {})
            .get("set", {})
            .get("X-Forwarded-Proto")
        )
        if forwarded_proto != "$http_x_forwarded_proto":
            fail(
                f"{route_id} must preserve oauth2-proxy's trusted "
                "X-Forwarded-Proto value."
            )
    for route_id in ("archideal-dealhost", "archideal-dealiot"):
        authorization = protected[route_id]["plugins"]["proxy-rewrite"]["headers"]["set"].get(
            "Authorization"
        )
        if authorization != "Bearer $http_x_forwarded_access_token":
            fail(f"{route_id} must forward oauth2-proxy's access token for introspection.")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--values", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--allow-example", action="store_true")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    output = args.output.resolve()
    if (
        output == ROOT
        or ROOT in output.parents
        or output in ROOT.parents
        or output == Path(output.anchor)
    ):
        fail("The rendered output must be outside and must not contain deploy/kubernetes.")
    values = load_values(args.values.resolve(), allow_example=args.allow_example)
    if output.exists():
        if not args.force:
            fail(f"Output already exists: {output}; pass --force to replace it.")
        marker = output / GENERATED_MARKER
        unexpected_entries = {
            entry.name
            for entry in output.iterdir()
            if entry.name not in {GENERATED_MARKER, "base", "overlays"}
        } if output.is_dir() else {output.name}
        if (
            not output.is_dir()
            or not marker.is_file()
            or marker.is_symlink()
            or marker.read_text(encoding="utf-8") != GENERATED_MARKER_CONTENT
            or unexpected_entries
        ):
            fail(
                f"Refusing to replace unmarked output: {output}; "
                "choose a new directory."
            )
        shutil.rmtree(output)
    output.mkdir(parents=True)
    (output / GENERATED_MARKER).write_text(
        GENERATED_MARKER_CONTENT,
        encoding="utf-8",
    )

    for tree_name in ("base", "overlays"):
        for source in (ROOT / tree_name).rglob("*"):
            if not source.is_file():
                continue
            relative = source.relative_to(ROOT)
            destination = output / relative
            destination.parent.mkdir(parents=True, exist_ok=True)
            text = source.read_text(encoding="utf-8")
            destination.write_text(
                render_text(text, values, relative),
                encoding="utf-8",
            )

    documents = validate_yaml_tree(output)
    validate_runtime_contracts(documents)
    print(f"Rendered and validated Kubernetes baseline in {output}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError, yaml.YAMLError) as exc:
        print(f"render error: {exc}", file=sys.stderr)
        raise SystemExit(2) from exc
