# Generated by Django 6.0.6 on 2026-07-20 07:08

import apps.hosting.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hosting", "0008_hostedapplication_revision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationversion",
            name="runtime_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="applicationversion",
            name="runtime_snapshot_digest",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.CreateModel(
            name="RuntimeEnvironment",
            fields=[
                (
                    "slug",
                    models.SlugField(max_length=63, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "orchestrator",
                    models.CharField(
                        default="kubernetes", editable=False, max_length=32
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "capabilities",
                    models.JSONField(
                        default=apps.hosting.models.default_runtime_capabilities
                    ),
                ),
                (
                    "policy",
                    models.JSONField(
                        default=apps.hosting.models.default_runtime_policy
                    ),
                ),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ModuleRuntimeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("spec", models.JSONField(default=dict)),
                ("spec_digest", models.CharField(max_length=64)),
                ("enabled", models.BooleanField(default=False)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runtime_profile",
                        to="hosting.module",
                    ),
                ),
            ],
            options={
                "ordering": ("module__slug",),
            },
        ),
        migrations.CreateModel(
            name="RuntimeRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manifest", models.JSONField()),
                ("manifest_digest", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runtime_release",
                        to="hosting.applicationversion",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RuntimeDeployment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "desired_state",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("stopped", "Stopped"),
                            ("absent", "Absent"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                (
                    "observed_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reconciling", "Reconciling"),
                            ("running", "Running"),
                            ("degraded", "Degraded"),
                            ("stopped", "Stopped"),
                            ("deleting", "Deleting"),
                            ("deleted", "Deleted"),
                            ("failed", "Failed"),
                            ("unknown", "Unknown"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "controller_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("secret_refs", models.JSONField(blank=True, default=dict)),
                ("scaling", models.JSONField(blank=True, default=dict)),
                ("generation", models.PositiveBigIntegerField(default=1)),
                ("observed_generation", models.PositiveBigIntegerField(default=0)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("last_reconciled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runtime_deployments",
                        to="hosting.hostedapplication",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_runtime_deployments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deployments",
                        to="hosting.runtimeenvironment",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deployments",
                        to="hosting.runtimerelease",
                    ),
                ),
            ],
            options={
                "ordering": ("application__name", "environment__name"),
            },
        ),
        migrations.CreateModel(
            name="RuntimeComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_id", models.PositiveBigIntegerField()),
                ("slug", models.SlugField(max_length=63)),
                ("image_digest", models.CharField(max_length=255)),
                ("desired_replicas", models.PositiveSmallIntegerField(default=1)),
                ("ready_replicas", models.PositiveSmallIntegerField(default=0)),
                ("available_replicas", models.PositiveSmallIntegerField(default=0)),
                ("state", models.CharField(default="pending", max_length=32)),
                ("health", models.CharField(default="unknown", max_length=32)),
                ("restart_count", models.PositiveIntegerField(default=0)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="hosting.runtimedeployment",
                    ),
                ),
            ],
            options={
                "ordering": ("slug",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("deployment", "slug"),
                        name="hosting_runtime_unique_deployment_slug",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RuntimeOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("deploy", "Deploy"),
                            ("configure", "Configure"),
                            ("start", "Start"),
                            ("stop", "Stop"),
                            ("restart", "Restart"),
                            ("scale", "Scale"),
                            ("undeploy", "Undeploy"),
                            ("log_snapshot", "Log snapshot"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "progress",
                    models.JSONField(
                        default=apps.hosting.models.default_operation_progress
                    ),
                ),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.JSONField(blank=True, null=True)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("request_hash", models.CharField(max_length=64)),
                ("target_generation", models.PositiveBigIntegerField(default=1)),
                (
                    "actor_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("controller_failures", models.PositiveSmallIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("leased_by", models.CharField(blank=True, default="", max_length=128)),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to="hosting.runtimedeployment",
                    ),
                ),
            ],
            options={
                "ordering": ("-requested_at",),
                "indexes": [
                    models.Index(
                        fields=["deployment", "-requested_at"],
                        name="hosting_runtime_operation_idx",
                    ),
                    models.Index(
                        fields=["status", "next_attempt_at"],
                        name="hosting_runtime_queue_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="runtimedeployment",
            index=models.Index(
                fields=["observed_state"], name="hosting_runtime_state_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="runtimedeployment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("application", "environment"),
                name="hosting_runtime_unique_active_app_environment",
            ),
        ),
        migrations.AddConstraint(
            model_name="runtimedeployment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("controller_id", ""), _negated=True),
                fields=("controller_id",),
                name="hosting_runtime_unique_controller_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="runtimedeployment",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="hosting_runtime_revision_positive",
            ),
        ),
    ]
